module.exports = [
  {
    id: 1,
    firstName: "Test",
    lastName: "Test1",
    phoneNo: "0769836354",
    email: "test@test1.com",
    job: "Junior / Entry level",
    remarks: null,
    reference: "facebook",
    is_career: true,
    is_business: false,
    domain: "vanzari",
    courses: ['Introducere în Atractivitate ca profesionist (Personal Branding și atractivitate în fața angajatorilor și clienților)'],
    date: "2021-11-07",
    year_month: "2021-11"
  },
  {
    id: 2,
    firstName: "Test",
    lastName: "Test2",
    phoneNo: "0784566354",
    email: "test@test2.com",
    job: "Freelancer / Soloprenor",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Resurse Umane",
    courses: ['Introducere în Marketing Digital și offline + Vânzări față în față, la telefon și în scris'],
    date: "2021-12-09",
    year_month: "2021-12"
  },
  {
    id: 3,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-11-04",
    year_month: "2021-11"
  },
  {
    id: 4,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-11-04",
    year_month: "2021-11"
  },
  {
    id: 5,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-12-04",
    year_month: "2021-12"
  },
  {
    id: 6,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Atractivitate ca profesionist (Personal Branding și atractivitate în fața angajatorilor și clienților)'],
    date: "2021-12-01",
    year_month: "2021-12"
  },
  {
    id: 7,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Atractivitate ca profesionist (Personal Branding și atractivitate în fața angajatorilor și clienților)'],
    date: "2021-12-21",
    year_month: "2021-12"
  },
  {
    id: 8,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-12-10",
    year_month: "2021-12"
  },
  {
    id: 9,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-11-13",
    year_month: "2021-11"
  },
  {
    id: 11,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-11-15",
    year_month: "2021-11"
  },
  {
    id: 12,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Marketing Digital și offline + Vânzări față în față, la telefon și în scris'],
    date: "2021-11-21",
    year_month: "2021-11"
  },
  {
    id: 13,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Marketing Digital și offline + Vânzări față în față, la telefon și în scris'],
    date: "2021-11-21",
    year_month: "2021-11"
  },
  {
    id: 14,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-11-15",
    year_month: "2021-11"
  },
  {
    id: 15,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Social Media (Strategie Social Media & Copywriting)'],
    date: "2021-11-13",
    year_month: "2021-11"
  },
  {
    id: 16,
    firstName: "Test",
    lastName: "Test3",
    phoneNo: "0786786354",
    email: "test@test3.com",
    job: "Urmeaza sa pornesc o afacere",
    remarks: null,
    reference: "linkedin",
    is_career: false,
    is_business: true,
    domain: "Financiar",
    courses: ['Introducere în Design Grafic - UX & UI (User Experience și User Interface)'],
    date: "2021-11-04",
    year_month: "2021-11"
  }
]