const REPLACE_STUDENT_EMAIL_ADDRESS = "FAKE_EMAIL_ADDRESS@replaced.r"
const REPLACE_STUDENT_FULL_NAME = "*Student Name Replaced*"

module.exports = {
  REPLACE_STUDENT_EMAIL_ADDRESS,
  REPLACE_STUDENT_FULL_NAME
}